[34m[1mwandb[0m: [32m[41mERROR[0m Attempted to change value of key "read_docs" from 250 to 100
[34m[1mwandb[0m: [32m[41mERROR[0m If you really want to do this, pass allow_val_change=True to config.update()
Traceback (most recent call last):
  File "train.py", line 31, in <module>
    config.read_docs = 100 # how many docs to load, at most
  File "/anaconda3/lib/python3.6/site-packages/wandb/wandb_config.py", line 217, in __setitem__
    key, val = self._sanitize(key, val)
  File "/anaconda3/lib/python3.6/site-packages/wandb/wandb_config.py", line 233, in _sanitize
    key, self._items[key], val))
wandb.wandb_config.ConfigError: Attempted to change value of key "read_docs" from 250 to 100
If you really want to do this, pass allow_val_change=True to config.update()
